# K8S installer
k8s_installer_etc_root: "/etc/k8s-installer"
k8s_installer_service_root: "{{ k8s_installer_etc_root }}/services"
k8s_installer_chart_root: "{{ k8s_installer_etc_root }}/charts"
k8s_installer_var_root: "/var/lib/k8s-installer"

# Containerd
containerd_root: "/var/lib/containerd"

# Docker
docker_root: "/var/lib/docker"

# Keepalived
enable_keepalived: true
enable_keepalived_vip1: true
keepalived_vip1: "123.123.123.123"
enable_keepalived_vip2: false
keepalived_vip2: "123.123.123.123"

# Cluster boot registry
cluster_boot_registry_domain_name: "cluster-boot-registry.example.com"
cluster_boot_registry_port: "5000"

# Nameserver
enable_nameserver: true
nameserver_ip_for_clients: "123.123.123.123"
nameserver_forwarders:
  - "8.8.8.8"
nameserver_zone: "example.com"
nameserver_a_records:
  - host: "@"
    ip: "123.123.123.123"
  - host: "*"
    ip: "123.123.123.123"
  - host: "cluster-boot-registry"
    ip: "123.123.123.123"
  - host: "ns1"
    ip: "123.123.123.123"
  - host: "internal.k8s"
    ip: "123.123.123.123"
  - host: "external.k8s"
    ip: "123.123.123.123"
  - host: "time"
    ip: "123.123.123.123"

# NTP
enable_ntp_server: true
ntp_server_offline_mode: false
ntp_server_address_for_clients: "time.example.com"

# K8S control plane
enable_k8s_haproxy: true
k8s_haproxy_port: 16443
k8s_apiserver_port: 6443
k8s_version: 1.27.9
k8s_control_plane_endpoint_address_internal: "internal.k8s.example.com"
k8s_control_plane_endpoint_address_external: "external.k8s.example.com"
k8s_service_cluster_ip_range: 10.96.0.0/12

# Helm packages...

# Flannel
enable_flannel: true
flannel_iface_can_reach: "123.123.123.123"

# Metallb
enable_metallb: true
ip_address_pools:
  - pool_name: "lb1"
    ip_address: "123.123.123.123"
    nodes:
      - "node1"
    interfaces:
      - "eth0"

# Ingress nginx
enable_ingress_nginx: true
ingresses:
  - ingress_class_name: lb1
    container_ports:
      http: 80
      https: 443
    enable_host_port: false
    controller_nodes:
      - "node1"
    service:
      enabled: true
      ip_address_pool_name: lb1
      ports:
        http: 80
        https: 443
