helm_chart_root: "{{ k8s_installer_etc_root }}/charts"

# K8S control plane
kubernetes_version: 1.27.9
k8s_control_plane_endpoint_address: "k8s.example.com"
k8s_control_plane_endpoint_port: "16443"
service_cluster_ip_range: 10.96.0.0/12

# Helm packages...

# Flannel
enable_flannel: true
flannel_iface_can_reach: "123.123.123.123"

# Metallb
enable_metallb: true
ip_address_pools:
  - pool_name: "lb1"
    ip_address: "123.123.123.123"
    nodes:
      - "node1"
    interfaces:
      - "eth0"

# Ingress nginx
enable_ingress_nginx: true
ingresses:
  - ingress_class_name: lb1
    container_ports:
      http: 80
      https: 443
    enable_host_port: false
    controller_nodes:
      - "node1"
    service:
      enabled: true
      ip_address_pool_name: lb1
      ports:
        http: 80
        https: 443
