- name: Set fact install_ca_supported from rhel8
  set_fact:
    install_ca_supported: true

- name: Create anchors directory
  file:
    path: /etc/pki/ca-trust/source/anchors
    state: directory
    mode: 0755
    recurse: true

- name: Create a symbolic link of k8s-installer-ca.crt
  file:
    src: "{{ k8s_installer_etc_root }}/k8s-installer-ca.crt"
    dest: /etc/pki/ca-trust/source/anchors/k8s-installer-ca.crt
    state: link

- name: Execute update-ca-trust
  command: "update-ca-trust"
