- name: Fail if distribution is not supported
  fail:
    msg: "{{ distribution }}{{ major_version }}.{{ minor_version }} is not supported"
  when:
    - minor_version | int > 7

- name: Set fact install_k8s_supported from centos8
  set_fact:
    install_k8s_supported: true

- name: Delete k8s rhel8 directory
  file:
    path: /tmp/k8s-installer/bin/k8s-node/rhel8
    state: absent

- name: Create k8s rhel8 directory
  file:
    path: /tmp/k8s-installer/bin/k8s-node/rhel8
    state: directory
    mode: 0755
    recurse: true

- name: From0
  block:
    - name: Copy k8s rhel8 files to host (from0)
      copy:
        src: ../../../../bin/k8s-node/rhel8/from0
        dest: /tmp/k8s-installer/bin/k8s-node/rhel8

    - name: Install k8s dependency packages (from0)
      shell: rpm -Uvh --oldpackage --replacepkgs /tmp/k8s-installer/bin/k8s-node/rhel8/from0/dependencies/*.rpm
      ignore_errors: true

    - name: Install k8s packages (from0)
      shell: rpm -Uvh /tmp/k8s-installer/bin/k8s-node/rhel8/from0/*.rpm
  when:
    - minor_version | int >= 0
    - minor_version | int <= 7
