- name: Get kubelet service status
  ansible.builtin.systemd:
    name: "kubelet"
  register: service_status

- name: Fail if kubelet is already installed
  fail:
    msg: "kubelet is already installed'"
  when:
    - service_status.status.LoadState != "not-found"
