- name: Set fact install_ntp_client_supported from centos8
  set_fact:
    install_ntp_client_supported: true

- name: Get chronyd service status
  ansible.builtin.systemd:
    name: "chronyd"
  register: service_status

- name: Fail if chronyd is already installed
  fail:
    msg: "chronyd is already installed'"
  when:
    - service_status.status.LoadState != "not-found"

- name: Delete ntp client rhel8 directory
  file:
    path: /tmp/k8s-installer/bin/ntp/client/rhel8
    state: absent

- name: Create ntp client rhel8 directory
  file:
    path: /tmp/k8s-installer/bin/ntp/client/rhel8
    state: directory
    mode: 0755
    recurse: true

- name: From0
  block:
    - name: Copy ntp client rhel8 files to host (from0)
      copy:
        src: ../../../../../bin/ntp/client/rhel8/from0
        dest: /tmp/k8s-installer/bin/ntp/client/rhel8

    - name: Install ntp client dependency packages (from0)
      shell: rpm -Uvh --oldpackage --replacepkgs /tmp/k8s-installer/bin/ntp/client/rhel8/from0/dependencies/*.rpm
      ignore_errors: true

    - name: Install ntp client packages (from0)
      shell: rpm -Uvh /tmp/k8s-installer/bin/ntp/client/rhel8/from0/*.rpm
  when:
    - minor_version | int >= 0
    - minor_version | int <= 7

- name: Set chrony.conf for k8s-installer ntp-server
  template:
    dest: "/etc/chrony.conf"
    src: chrony.conf.j2
    owner: root
    mode: 0644

- name: Restart chronyd
  systemd:
    name: chronyd
    state: restarted
    enabled: yes
    daemon-reload: yes
    masked: no
