- name: Set fact install_ntp_client_supported from ubuntu2204
  set_fact:
    install_ntp_client_supported: true

- name: Get systemd-timesyncd service status
  ansible.builtin.systemd:
    name: "systemd-timesyncd"
  register: service_status

- name: Fail if systemd-timesyncd is already installed
  fail:
    msg: "systemd-timesyncd is already installed'"
  when:
    - service_status.status.LoadState != "not-found"

- name: Delete ntp client ubuntu2204 directory
  file:
    path: /tmp/k8s-installer/bin/ntp/client/ubuntu2204
    state: absent

- name: Create ntp client ubuntu2204 directory
  file:
    path: /tmp/k8s-installer/bin/ntp/client/ubuntu2204
    state: directory
    mode: 0755
    recurse: true

- name: From0
  block:
    - name: Copy ntp client ubuntu2204 files to host (from0)
      copy:
        src: ../../../../../bin/ntp/client/ubuntu2204/from0
        dest: /tmp/k8s-installer/bin/ntp/client/ubuntu2204

    - name: Install ntp client dependency packages (from0)
      shell: dpkg -i /tmp/k8s-installer/bin/ntp/client/ubuntu2204/from0/dependencies/*.deb
      ignore_errors: true

    - name: Install ntp client packages (from0)
      shell: dpkg -i /tmp/k8s-installer/bin/ntp/client/ubuntu2204/from0/*.deb
  when:
    - minor_version | int >= 0
    - minor_version | int <= 5

- name: Set timesyncd.conf for k8s-installer ntp-server
  template:
    dest: "/etc/systemd/timesyncd.conf"
    src: timesyncd.conf.j2
    owner: root
    mode: 0644

- name: Restart systemd-timesyncd
  systemd:
    name: systemd-timesyncd
    state: restarted
    enabled: yes
    daemon-reload: yes
    masked: no
