- name: Verify module path exists
  file:
    path: /etc/modules-load.d
    state: directory
    mode: 0755

- name: Enable modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter

- name: Persist modules
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
    mode: 0644
