- name: Include tasks preflight.yml
  include_tasks: preflight.yml

- name: Include tasks ubuntu2204-install.yml
  include_tasks: ubuntu2204-install.yml
  when:
    - ansible_distribution in ["Ubuntu"]
    - major_version == "22.04"

- name: Include tasks rhel8-install.yml
  include_tasks: rhel8-install.yml
  when:
    - ansible_distribution in ["RedHat"]
    - major_version == "8"

- name: Include tasks centos8-install.yml
  include_tasks: centos8-install.yml
  when:
    - ansible_distribution in ["CentOS"]
    - major_version == "8"

- name: Fail if distribution is not supported
  fail:
    msg: "{{ distribution }}{{ major_version }}.{{ minor_version }} is not supported"
  when: install_k8s_supported | default(False) | bool == false

- name: Include tasks swapoff.yml
  include_tasks: swapoff.yml

- name: Include tasks enable-modules.yml
  include_tasks: enable-modules.yml

- name: Include tasks setup-sysctl-params.yml
  include_tasks: setup-sysctl-params.yml

- name: Include tasks selinux-permissive-mode.yml
  include_tasks: selinux-permissive-mode.yml
  when: ansible_os_family == "RedHat"

- name: Enable service kubelet
  systemd:
    state: stopped
    enabled: true
    name: kubelet

- name: Set k8s-resolv.conf
  template:
    dest: "/etc/k8s-resolv.conf"
    src: k8s-resolv.conf.j2
    owner: root
    mode: 0644

- name: Add route for kubernetes service
  command: "ip route add {{ service_cluster_ip_range }} via {{ k8s_ip }} dev {{ k8s_interface }}"

- name: Set crictl configuration
  template:
    dest: "/etc/crictl.yaml"
    src: crictl.yaml.j2
    owner: root
    mode: 0644

- name: Install helm
  copy:
    src: ../../../../bin/k8s-node/helm
    dest: /usr/local/bin
    mode: 0555
