- name: Get kubelet service status
  ansible.builtin.systemd:
    name: "kubelet"
  register: service_status

- name: Fail if kubelet is already installed
  fail:
    msg: "kubelet is already installed'"
  when:
    - service_status.status.LoadState != "not-found"

- name: Fail if k8s_interface is invalid
  fail:
    msg: "'{{ k8s_interface | default('undefined') }}' is invalid interface"
  when: k8s_interface is undefined or
    k8s_interface | length <= 0
