- name: Fail if distribution is not supported
  fail:
    msg: "{{ distribution }}{{ major_version }}.{{ minor_version }} is not supported"
  when:
    - minor_version | int > 4

- name: Set fact install_k8s_supported from ubuntu2204
  set_fact:
    install_k8s_supported: true

- name: Delete k8s ubuntu2204 directory
  file:
    path: /tmp/k8s-installer/bin/k8s-node/ubuntu2204
    state: absent

- name: Create k8s ubuntu2204 directory
  file:
    path: /tmp/k8s-installer/bin/k8s-node/ubuntu2204
    state: directory
    mode: 0755
    recurse: true

- name: From0
  block:
    - name: Copy k8s ubuntu2204 files to host (from0)
      copy:
        src: ../../../../bin/k8s-node/ubuntu2204/from0
        dest: /tmp/k8s-installer/bin/k8s-node/ubuntu2204

    - name: Install k8s dependency packages (from0)
      shell: dpkg -i /tmp/k8s-installer/bin/k8s-node/ubuntu2204/from0/dependencies/*.deb
      ignore_errors: true

    - name: Install k8s packages (from0)
      shell: dpkg -i /tmp/k8s-installer/bin/k8s-node/ubuntu2204/from0/*.deb
  when:
    - minor_version | int >= 0
    - minor_version | int <= 4

- name: Set kubelet 10-kubeadm.conf
  template:
    dest: "/usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf"
    src: ubuntu2204-10-kubeadm.conf.j2
    owner: root
    mode: 0644
