- name: Create flannel directory
  file:
    path: "{{ helm_chart_root }}/flannel"
    state: directory

- name: Copy flannel.tgz
  copy:
    src: ../../../../bin/k8s-node/packages/flannel.tgz
    dest: "{{ helm_chart_root }}/flannel"

- name: Set values.yml
  template:
    dest: "{{ helm_chart_root }}/flannel/values.yml"
    src: flannel-values.yml.j2
    owner: root
    mode: 0644

- name: Create kube-flannel namespace
  command: "kubectl create ns kube-flannel"

- name: Label the namespace
  command: "kubectl label --overwrite ns kube-flannel pod-security.kubernetes.io/enforce=privileged"

- name: Install flannel
  command: "helm install --namespace kube-flannel flannel {{ helm_chart_root }}/flannel/flannel.tgz -f {{ helm_chart_root }}/flannel/values.yml"
