- name: Include tasks preflight.yml
  include_tasks: preflight.yml

- name: Include tasks install-flannel.yml
  include_tasks: install-flannel.yml
  when: enable_flannel

- name: Include tasks install-metallb.yml
  include_tasks: install-metallb.yml
  when: enable_metallb
