- name: Stat nameserver directory
  stat:
    path: "{{ docker_compose_root }}/nameserver"
  register: nameserver_directory

- name: Fail if nameserver directory already exist
  fail:
    msg: "Directory \"{{ docker_compose_root }}/nameserver\" already exist"
  when: nameserver_directory.stat.exists
