- name: Include tasks preflight.yml
  include_tasks: preflight.yml

- name: Run create_k8s_ip_to_node_name_map module
  create_k8s_ip_to_node_name_map:
    hostvars: "{{ hostvars }}"
  register: create_k8s_ip_to_node_name_map_result

- name: Parse addresses of cluster's nodes
  command: "{{cmd}}"
  register: node_addresses
  changed_when: false
  vars:
    cmd: !unsafe kubectl get nodes -o go-template='{{range .items}}["{{.metadata.name}}"{{range .status.addresses}}, "{{.address}}"{{end}}]{{"\n"}}{{end}}'

- name: Run create_k8s_hostname_to_addresses_map module
  create_k8s_hostname_to_addresses_map:
    node_addresses: "{{ node_addresses.stdout_lines | map('from_json') }}"
  register: create_k8s_hostname_to_addresses_map_result

- name: Run create_node_name_to_k8s_hostname_map module
  create_node_name_to_k8s_hostname_map:
    k8s_ip_to_node_name_map: "{{ create_k8s_ip_to_node_name_map_result.k8s_ip_to_node_name_map }}"
    k8s_hostname_to_addresses_map: "{{ create_k8s_hostname_to_addresses_map_result.k8s_hostname_to_addresses_map }}"
  register: create_node_name_to_k8s_hostname_map_result

- name: Set node_name_to_k8s_hostname_map variable
  set_fact:
    node_name_to_k8s_hostname_map: "{{ create_node_name_to_k8s_hostname_map_result.node_name_to_k8s_hostname_map }}"
    k8s_hostname_to_node_name_map: "{{ create_node_name_to_k8s_hostname_map_result.k8s_hostname_to_node_name_map }}"
