- name: Delete keepalived tmp bin directory
  file:
    path: /tmp/k8s-installer/bin/keepalived
    state: absent

- name: Create keepalived tmp bin directory
  file:
    path: /tmp/k8s-installer/bin/keepalived
    state: directory
    mode: 0755
    recurse: true

- name: Copy keepalived-2.0.20-image.tar file to host
  copy:
    src: ../../../../bin/keepalived/keepalived-2.0.20-image.tar
    dest: /tmp/k8s-installer/bin/keepalived

- name: Load keepalived-2.0.20-image.tar
  command: docker load -i /tmp/k8s-installer/bin/keepalived/keepalived-2.0.20-image.tar

- name: Create keepalived directory
  file:
    path: "{{ k8s_installer_service_root }}/keepalived"
    state: directory

- name: Set compose.yml
  template:
    dest: "{{ k8s_installer_service_root }}/keepalived/compose.yml"
    src: keepalived-compose.yml.j2
    owner: root
    mode: 0644

- name: Set keepalived.conf
  template:
    dest: "{{ k8s_installer_service_root }}/keepalived/keepalived.conf"
    src: keepalived.conf.j2
    owner: root
    mode: 0644

- name: Set check_node.sh
  template:
    dest: "{{ k8s_installer_service_root }}/keepalived/check_node.sh"
    src: check_node.sh.j2
    owner: root
    mode: 0755

- name: Run the keepalived service
  command: "docker compose -f {{ k8s_installer_service_root }}/keepalived/compose.yml up -d"
