- name: Get systemd-resolved service status
  ansible.builtin.systemd:
    name: "systemd-resolved"
  register: service_status

- name: Disable the systemd-resolved service
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: false
    masked: no
  when:
    - service_status.status.LoadState != "not-found"
