- hosts: all:!localhost
  gather_facts: false
  any_errors_fatal: true
  vars:
    vars_path_arg: "--vars-path {{ ki_tmp_vars_path }}"
  tasks:
    - name: Execute check-node-state.sh
      shell: "sudo {{ ki_env_scripts_path }}/all-node/check-node-state.sh {{ vars_path_arg }}"
