- hosts: all:!localhost
  gather_facts: false
  any_errors_fatal: true
  vars:
    vars_path_arg: "--vars-path {{ ki_tmp_vars_path }}"
  tasks:
    - when: target_node is none or inventory_hostname == target_node
      block:
        - name: Execute setup-ntp-client.sh
          shell: "sudo {{ ki_env_scripts_path }}/all-node/ntp-client/setup-ntp-client.sh {{ vars_path_arg }}"
