- hosts: all:!localhost
  gather_facts: false
  any_errors_fatal: true
  vars:
    vars_path_arg: "--vars-path {{ ki_tmp_vars_path }}"
  tasks:
    - name: Execute setup-resolv-conf.sh
      shell: "sudo {{ ki_env_scripts_path }}/all-node/resolv-conf/setup-resolv-conf.sh {{ vars_path_arg }}"
