- name: Set backend_servers variable
  set_fact:
    backend_servers: "{{ groups['control_plane_k8s_node'] }}"
  when: backend_servers is undefined

- name: Delete k8s-haproxy tmp bin directory
  file:
    path: /tmp/k8s-installer/bin/k8s-haproxy
    state: absent

- name: Create k8s-haproxy tmp bin directory
  file:
    path: /tmp/k8s-installer/bin/k8s-haproxy
    state: directory
    mode: 0755
    recurse: true

- name: Copy haproxy-2.6-image.tar file to host
  copy:
    src: ../../../../bin/k8s-haproxy/haproxy-2.6-image.tar
    dest: /tmp/k8s-installer/bin/k8s-haproxy

- name: Load haproxy-2.6-image.tar
  command: docker load -i /tmp/k8s-installer/bin/k8s-haproxy/haproxy-2.6-image.tar

- name: Create k8s-haproxy directory
  file:
    path: "{{ k8s_installer_service_root }}/k8s-haproxy"
    state: directory

- name: Set compose.yml
  template:
    dest: "{{ k8s_installer_service_root }}/k8s-haproxy/compose.yml"
    src: haproxy-compose.yml.j2
    owner: root
    mode: 0644

- name: Set haproxy.cfg
  template:
    dest: "{{ k8s_installer_service_root }}/k8s-haproxy/haproxy.cfg"
    src: haproxy.cfg.j2
    owner: root
    mode: 0644

- name: Run the haproxy service
  command: "docker compose -f {{ k8s_installer_service_root }}/k8s-haproxy/compose.yml up -d"
