- name: Get docker service status
  ansible.builtin.systemd:
    name: "docker"
  register: service_status

- name: Fail if docker is already installed
  fail:
    msg: "docker is already installed'"
  when:
    - service_status.status.LoadState != "not-found"
