- name: Stat cluster-boot-registry directory
  stat:
    path: "{{ docker_compose_root }}/cluster-boot-registry"
  register: cluster_boot_registry_directory

- block:
  - name: Remove cluster-boot-registry service
    command: "docker compose -f {{ docker_compose_root }}/cluster-boot-registry/compose.yml down"

  - name: Remove cluster-boot-registry directory
    file:
      path: "{{ docker_compose_root }}/cluster-boot-registry"
      state: absent

  - name: Remove cluster-boot-registry var directory
    file:
      path: "{{ k8s_installer_var_root }}/cluster-boot-registry"
      state: absent
  when: cluster_boot_registry_directory.stat.exists
