- name: Stat k8s-haproxy directory
  stat:
    path: "{{ k8s_installer_service_root }}/k8s-haproxy"
  register: k8s_haproxy_directory

- block:
  - name: Remove k8s-haproxy service
    command: "docker compose -f {{ k8s_installer_service_root }}/k8s-haproxy/compose.yml down"

  - name: Remove k8s-haproxy directory
    file:
      path: "{{ k8s_installer_service_root }}/k8s-haproxy"
      state: absent
  when: k8s_haproxy_directory.stat.exists
