- name: Stat keepalived directory
  stat:
    path: "{{ k8s_installer_service_root }}/keepalived"
  register: keepalived_directory

- block:
    - name: Remove keepalived service
      command: "docker compose -f {{ k8s_installer_service_root }}/keepalived/compose.yml down"

    - name: Remove keepalived directory
      file:
        path: "{{ k8s_installer_service_root }}/keepalived"
        state: absent
  when: keepalived_directory.stat.exists
