- name: Fail if target_node variable is undefined
  fail:
    msg: "target_node variable is undefined"
  when: target_node is undefined

- name: Fail if target_node variable is control plane node
  fail:
    msg: Can not delete control plane node
  when:
    - target_node in (groups['control_plane_k8s_node'])

- name: Set target_node_k8s_ip variable
  set_fact:
    target_node_k8s_ip: "{{ hostvars[target_node]['k8s_ip'] }}"

- name: Fail if target_node_k8s_ip variable is invalid
  fail:
    msg: "target_node_k8s_ip variable '{{ target_node_k8s_ip | default('undefined') }}' is invalid ip"
  when: (target_node_k8s_ip | default('undefined')) is not ansible.utils.ipv4

- name: Fail if host is not first_control_plane_k8s_node
  fail:
    msg: "host is not first_control_plane_k8s_node"
  when: inventory_hostname != first_control_plane_k8s_node
