- name: Fail if target_node variable is undefined
  fail:
    msg: "target_node variable is undefined"
  when: target_node is undefined

- name: Fail if target_node variable is control plane node
  fail:
    msg: Can not delete control plane node
  when:
    - target_node in (groups['control_plane_k8s_node'])

- name: Fail if host is not first_control_plane_k8s_node
  fail:
    msg: "host is not first_control_plane_k8s_node"
  when: inventory_hostname != first_control_plane_k8s_node

- include_role:
    name: k8s/create-node-name-to-k8s-hostname-map-fact

- name: Fail if node_name_to_k8s_hostname_map[target_node] is undefined
  fail: {}
  when: node_name_to_k8s_hostname_map[target_node] is undefined
