- import_playbook: tasks/check-k8s-installer-setup.yml

- import_playbook: tasks/sync-ansible.yml

- import_playbook: tasks/preflight-playbook.yml
  vars:
    playbook: "backup-etcd"

- import_playbook: tasks/gather-facts.yml

- import_playbook: tasks/validate-hostvars.yml

- import_playbook: tasks/setup-vars-file.yml

- import_playbook: tasks/backup-etcd.yml

- import_playbook: tasks/reset-vars-file.yml
