- import_playbook: tasks/begin-playbook.yml
  vars:
    playbook: "push-user-registry-images"

- import_playbook: tasks/prepare-vars.yml

- import_playbook: tasks/push-user-registry-images.yml

- import_playbook: tasks/check-user-registry.yml

- import_playbook: tasks/reset-vars-file.yml
