- import_playbook: tasks/begin-playbook.yml
  vars:
    playbook: "renew-certs"

- import_playbook: tasks/prepare-vars.yml

- import_playbook: tasks/backup-etcd.yml

- import_playbook: tasks/renew-k8s-certs.yml

- import_playbook: tasks/reset-vars-file.yml

- import_playbook: tasks/check-cert-expiry.yml
