- import_playbook: tasks/begin-playbook.yml
  vars:
    playbook: "update-cluster"

- import_playbook: tasks/prepare-vars.yml

- import_playbook: tasks/diff-applied-vars.yml

- import_playbook: tasks/apply-service-var-changes.yml

- import_playbook: tasks/apply-kubelet-var-changes.yml

- import_playbook: tasks/apply-cluster-config-var-changes.yml

- import_playbook: tasks/record-applied-state.yml

- import_playbook: tasks/reset-vars-file.yml
