- name: Stat cluster-boot-registry directory
  stat:
    path: "{{ k8s_installer_service_root }}/cluster-boot-registry"
  register: cluster_boot_registry_directory

- name: Fail if cluster-boot-registry directory already exist
  fail:
    msg: "Directory \"{{ k8s_installer_service_root }}/cluster-boot-registry\" already exist"
  when: cluster_boot_registry_directory.stat.exists


- name: Fail if tls_cert is invalid
  fail:
    msg: "'{{ tls_cert | default('undefined') }}' is invalid certificate"
  when: tls_cert is undefined or
    tls_cert | length <= 0

- name: Fail if tls_key is invalid
  fail:
    msg: "'{{ tls_key | default('undefined') }}' is invalid certificate"
  when: tls_key is undefined or
    tls_key | length <= 0
