- name: Include tasks preflight.yml
  include_tasks: preflight.yml

- name: Load ca_cert variable from ca.crt
  slurp:
    src: "{{ k8s_installer_etc_root }}/tls-certificate-issue-tool/output/ca.crt"
  register: ca_cert_slurp

- name: Set ca_cert variable
  set_fact:
    ca_cert: "{{ ca_cert_slurp.content | b64decode }}"
