- name: Fail if host is not in tls_cert_issuer group
  fail:
    msg: "host is not in tls_cert_issuer group"
  when: inventory_hostname not in groups['tls_cert_issuer']

- name: Stat ca.crt
  stat:
    path: "{{ k8s_installer_etc_root }}/tls-certificate-issue-tool/output/ca.crt"
  register: output_ca_crt

- name: Fail if ca.crt does not exist
  fail:
    msg: "File \"{{ k8s_installer_etc_root }}/tls-certificate-issue-tool/output/ca.crt\" does not exist"
  when: not output_ca_crt.stat.exists
