- name: Fail if first_control_plane_k8s_node is invalid
  fail:
    msg: "'{{ first_control_plane_k8s_node | default('undefined') }}' is invalid host"
  when: first_control_plane_k8s_node is undefined or
    first_control_plane_k8s_node | length <= 0

- name: Parse addresses of cluster's nodes
  command: kubectl get nodes -o=jsonpath-as-json='{.items[*].status.addresses[*].address}'
  register: nodes_addresses
  delegate_to: "{{ first_control_plane_k8s_node }}"
  changed_when: false

- name: Fail if k8s_ip is invalid
  fail:
    msg: "'{{ k8s_ip | default('undefined') }}' is invalid ip"
  when: (k8s_ip | default('undefined')) is not ansible.utils.ipv4

- name: Fail if the node is already attached
  fail:
    msg: "The node is already attached"
  when: k8s_ip in (nodes_addresses.stdout | from_json)

- name: Get kubelet service status
  ansible.builtin.systemd:
    name: "kubelet"
  register: service_status

- name: Fail if kubelet is already running
  fail:
    msg: "Kubelet is already running on the node '{{ k8s_node_to_add }}'"
  when:
    - service_status.status.ActiveState == "active"

- name: Fail if k8s_interface is invalid
  fail:
    msg: "'{{ k8s_interface | default('undefined') }}' is invalid interface"
  when: k8s_interface is undefined or
    k8s_interface | length <= 0

- name: Fail if k8s_control_plane_endpoint_address_internal is invalid
  fail:
    msg: "'{{ k8s_control_plane_endpoint_address_internal | default('undefined') }}' is invalid"
  when: k8s_control_plane_endpoint_address_internal is undefined or
    k8s_control_plane_endpoint_address_internal | length <= 0
