- name: Include tasks preflight.yml
  include_tasks: preflight.yml

- name: Uninstall helm
  file:
    path: "/usr/local/bin/helm"
    state: absent

- name: Remove crictl.yaml
  file:
    path: "/etc/crictl.yaml"
    state: absent

- name: Remove k8s-resolv.conf
  file:
    path: "/etc/k8s-resolv.conf"
    state: absent

- name: Remove k8s packages on debian os family
  command: |-
    apt remove -y --purge --allow-change-held-packages \
    kubeadm \
    kubectl \
    kubelet \
    cri-tools \
    kubernetes-cni
  ignore_errors: true
  when: ansible_os_family == "Debian"

- name: Remove k8s packages on redhat os family
  command: |-
    yum erase -y \
    kubeadm \
    kubectl \
    kubelet \
    cri-tools \
    kubernetes-cni
  when: ansible_os_family == "RedHat"
