- name: Fail if k8s_ip is invalid
  fail:
    msg: "'{{ k8s_ip | default('undefined') }}' is invalid ip"
  when: (k8s_ip | default('undefined')) is not ansible.utils.ipv4

- name: Fail if k8s_interface is invalid
  fail:
    msg: "'{{ k8s_interface | default('undefined') }}' is invalid interface"
  when: k8s_interface is undefined or
    k8s_interface | length <= 0
