- name: Fail if distribution is not supported
  fail:
    msg: "{{ ansible_distribution }}{{ ansible_distribution_version }} is not supported"
  when:
    - minor_version | int > 7

- name: Set fact install_docker_supported from rhel8
  set_fact:
    install_docker_supported: true

- name: Delete docker rhel8 directory
  file:
    path: /tmp/k8s-installer/bin/docker-node/docker/rhel8
    state: absent

- name: Create docker rhel8 directory
  file:
    path: /tmp/k8s-installer/bin/docker-node/docker/rhel8
    state: directory
    mode: 0755
    recurse: true

- name: From0
  block:
    - name: Copy docker rhel8 files to host (from0)
      copy:
        src: ../../../../bin/docker-node/docker/rhel8/from0
        dest: /tmp/k8s-installer/bin/docker-node/docker/rhel8

    - name: Install docker dependency packages (from0)
      shell: rpm -Uvh --oldpackage --replacepkgs /tmp/k8s-installer/bin/docker-node/docker/rhel8/from0/dependencies/*.rpm
      ignore_errors: true

    - name: Install docker packages (from0)
      shell: rpm -Uvh /tmp/k8s-installer/bin/docker-node/docker/rhel8/from0/*.rpm
  when:
    - minor_version | int >= 0
    - minor_version | int <= 1

- name: From2
  block:
    - name: Copy docker rhel8 files to host (from2)
      copy:
        src: ../../../../bin/docker-node/docker/rhel8/from2
        dest: /tmp/k8s-installer/bin/docker-node/docker/rhel8

    - name: Install docker dependency packages (from2)
      shell: rpm -Uvh --oldpackage --replacepkgs /tmp/k8s-installer/bin/docker-node/docker/rhel8/from2/dependencies/*.rpm
      ignore_errors: true

    - name: Install docker packages (from2)
      shell: rpm -Uvh /tmp/k8s-installer/bin/docker-node/docker/rhel8/from2/*.rpm
  when:
    - minor_version | int >= 2
    - minor_version | int <= 5

- name: From6
  block:
    - name: Copy docker rhel8 files to host (from6)
      copy:
        src: ../../../../bin/docker-node/docker/rhel8/from6
        dest: /tmp/k8s-installer/bin/docker-node/docker/rhel8

    - name: Install docker dependency packages (from6)
      shell: rpm -Uvh --oldpackage --replacepkgs /tmp/k8s-installer/bin/docker-node/docker/rhel8/from6/dependencies/*.rpm
      ignore_errors: true

    - name: Install docker packages (from6)
      shell: rpm -Uvh /tmp/k8s-installer/bin/docker-node/docker/rhel8/from6/*.rpm
  when:
    - minor_version | int >= 6
    - minor_version | int <= 7

- name: Set docker service unit
  template:
    dest: "/usr/lib/systemd/system/docker.service"
    src: rhel8-docker.service.j2
    owner: root
    mode: 0644

- name: Install nvidia-container-toolkit
  block:
    - name: Delete nvidia-container-toolkit rhel8 directory
      file:
        path: /tmp/k8s-installer/bin/docker-node/nvidia-container-toolkit/rhel8
        state: absent

    - name: Create nvidia-container-toolkit rhel8 directory
      file:
        path: /tmp/k8s-installer/bin/docker-node/nvidia-container-toolkit/rhel8
        state: directory
        mode: 0755
        recurse: true

    - name: From0
      block:
        - name: Copy nvidia-container-toolkit rhel8 files to host (from0)
          copy:
            src: ../../../../bin/docker-node/nvidia-container-toolkit/rhel8/from0
            dest: /tmp/k8s-installer/bin/docker-node/nvidia-container-toolkit/rhel8

        - name: Install nvidia-container-toolkit packages (from0)
          shell: rpm -Uvh /tmp/k8s-installer/bin/docker-node/nvidia-container-toolkit/rhel8/from0/*.rpm
      when:
        - minor_version | int >= 0
        - minor_version | int <= 7
  when:
    - nvidia_gpu_node | default(False) | bool == true
