- name: Set fact uninstall_ca_supported from ubuntu2204
  set_fact:
    uninstall_ca_supported: true

- name: Delete a symbolic link of k8s-installer-ca.crt
  file:
    path: /usr/local/share/ca-certificates/k8s-installer-ca.crt
    state: absent

- name: Execute update-ca-certificates
  command: "update-ca-certificates"
