- block:
    - name: Check whether metallb is installed
      command: "helm get notes -n metallb metallb"
      ignore_errors: true
      register: helm_get_metallb

    - block:
        - name: Delete ip address pools in kubernetes
          command: "kubectl delete -f {{ k8s_installer_chart_root }}/metallb/ip-pools"

        - name: Uninstall metallb
          command: "helm uninstall --namespace metallb metallb"

        - name: Delete metallb namespace
          command: "kubectl delete ns metallb"
      when: helm_get_metallb.rc == 0
  when: not skip_uninstall_from_cluster

- name: Remove metallb directory
  file:
    path: "{{ k8s_installer_chart_root }}/metallb"
    state: absent
