- hosts: all
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: Set_fact variable[\"playbook\"]
      set_fact:
        playbook: "setup-k8s-charts"

    - name: Set_fact variable[\"skip_resetting_vars_file\"]
      set_fact:
        skip_resetting_vars_file: ""
      when: srvf is defined
