- name: Iptables flush all tables
  iptables:
    table: "{{ item }}"
    flush: yes
  with_items:  [ 'filter', 'nat', 'mangle' ]

- name: Get docker service status
  ansible.builtin.systemd:
    name: "docker"
  register: service_status

- name: Restart docker
  systemd:
    name: docker
    state: restarted
    enabled: yes
    daemon-reload: yes
    masked: no
  when:
    - service_status.status.ActiveState == "active"
