- name: Include tasks ubuntu2204-install.yml
  include_tasks: ubuntu2204-install.yml
  when:
    - ansible_distribution in ["Ubuntu"]
    - major_version == "22.04"

- name: Include tasks rhel8-install.yml
  include_tasks: rhel8-install.yml
  when:
    - ansible_distribution in ["RedHat"]
    - major_version == "8"

- name: Include tasks centos8-install.yml
  include_tasks: centos8-install.yml
  when:
    - ansible_distribution in ["CentOS"]
    - major_version == "8"

- name: Fail if distribution is not supported
  fail:
    msg: "{{ ansible_distribution }}{{ ansible_distribution_version }} is not supported"
  when: set_ntp_client_conf_supported | default(False) | bool == false
