- name: Set fact set_ntp_client_conf_supported from rhel8
  set_fact:
    set_ntp_client_conf_supported: true

- name: Set chrony.conf for k8s-installer ntp-server
  template:
    dest: "/etc/chrony.conf"
    src: k8s-installer-chrony.conf.j2
    owner: root
    mode: 0644
  when: enable_ntp_server

- name: Set chrony.conf for internet ntp-server
  template:
    dest: "/etc/chrony.conf"
    src: internet-chrony.conf.j2
    owner: root
    mode: 0644
  when: not enable_ntp_server

- name: Restart chronyd
  systemd:
    name: chronyd
    state: restarted
    enabled: yes
    daemon-reload: yes
    masked: no
