- name: Include tasks preflight.yml
  include_tasks: preflight.yml

- name: Create tls-certificate-issue-tool directory
  file:
    path: "{{ k8s_installer_etc_root }}/tls-certificate-issue-tool"
    state: directory

- name: Copy tls-certificate-issue-tool contents to host
  copy:
    src: ../../../../scripts/tls-certificate-issue-tool
    dest: "{{ k8s_installer_etc_root }}"
    mode: '0755'

- name: Create ca certificate
  shell: "{{ k8s_installer_etc_root }}/tls-certificate-issue-tool/create-ca-crt.sh --common-name k8s-installer --days 3650"
