- name: Fail if host is not in tls_cert_issuer group
  fail:
    msg: "host is not in tls_cert_issuer group"
  when: inventory_hostname not in groups['tls_cert_issuer']

- name: Stat tls-certificate-issue-tool directory
  stat:
    path: "{{ k8s_installer_etc_root }}/tls-certificate-issue-tool"
  register: tls_certificate_issue_tool_directory

- name: Fail if tls-certificate-issue-tool directory already exist
  fail:
    msg: "Directory \"{{ k8s_installer_etc_root }}/tls-certificate-issue-tool\" already exist"
  when: tls_certificate_issue_tool_directory.stat.exists
