- name: Stat ntp-server directory
  stat:
    path: "{{ k8s_installer_service_root }}/ntp-server"
  register: ntp_server_directory

- block:
  - name: Remove ntp-server service
    command: "docker compose -f {{ k8s_installer_service_root }}/ntp-server/compose.yml down"

  - name: Remove ntp-server directory
    file:
      path: "{{ k8s_installer_service_root }}/ntp-server"
      state: absent
  when: ntp_server_directory.stat.exists
