- name: Stat ntp-server directory
  stat:
    path: "{{ k8s_installer_service_root }}/ntp-server"
  register: ntp_server_directory

- name: Fail if ntp-server directory already exist
  fail:
    msg: "Directory \"{{ k8s_installer_service_root }}/ntp-server\" already exist"
  when: ntp_server_directory.stat.exists
