- hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - include_role:
        name: preflight/ensure-bin-directory-exist

- hosts: all:localhost
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - include_role:
        name: gather-facts

- hosts: tls_cert_issuer
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - include_role:
        name: certificate/set-ca-cert-variable
    - include_role:
        name: certificate/set-tls-cert-variable
      vars:
        tls_domain_name: "{{ cluster_boot_registry_domain_name }}"

- hosts: cluster_boot_registry
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - include_role:
        name: certificate/install-ca-cert
      vars:
        ca_cert: "{{ hostvars[groups['tls_cert_issuer'] | first]['ca_cert'] }}"
    - include_role:
        name: nameserver/set-resolv-conf
    - block:
      - include_role:
          name: ntp/client/uninstall
      - include_role:
          name: ntp/client/install
      when: enable_ntp_server
    - name: Get docker service status
      ansible.builtin.systemd:
        name: "docker"
      register: service_status
    - include_role:
        name: docker/install
      when:
        - service_status.status.LoadState == "not-found"
    - include_role:
        name: cluster-boot-registry/uninstall
    - include_role:
        name: cluster-boot-registry/install
      vars:
        tls_cert: "{{ hostvars[groups['tls_cert_issuer'] | first]['tls_cert'] }}"
        tls_key: "{{ hostvars[groups['tls_cert_issuer'] | first]['tls_key'] }}"
