- hosts: localhost
  become: true
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - include_role:
        name: preflight/ensure-bin-directory-exist

- hosts: all:localhost
  become: true
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - include_role:
        name: gather-facts

- hosts: k8s_node
  become: true
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - include_role:
        name: k8s/preflight
    - include_role:
        name: k8s/uninstall-packages
      vars:
        skip_uninstall_from_cluster: false
      when: inventory_hostname == first_control_plane_k8s_node
