- hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: Fail if node variable is invalid
      fail:
        msg: "node variable '{{ node | default('undefined') }}' is invalid host"
      when: node is undefined or
        node | length <= 0
    - name: Fail if node variable does not belong to k8s_node group
      fail:
        msg: "node variable '{{ node }}' does not belong to k8s_node group"
      when: node not in groups['k8s_node']

- hosts: all:localhost
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - include_role:
        name: gather-facts

- hosts: "{{ node }}"
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - include_role:
        name: k8s/preflight

- hosts: k8s_node
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - block:
      - include_role:
          name: k8s/preflight
      - include_role:
          name: k8s/delete-node-from-cluster
        vars:
          target_node: "{{ node }}"
      when:
        - inventory_hostname == first_control_plane_k8s_node
        - not (skip_delete_node_from_cluster | default(False) | bool)

- hosts: "{{ node }}"
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - include_role:
        name: k8s/reset-kubelet
    - include_role:
        name: k8s/uninstall-kubelet
    - include_role:
        name: docker/uninstall
      when:
        - "'cluster_boot_registry' not in group_names"
        - "'keepalived' not in group_names"
        - "'nameserver' not in group_names"
        - "'k8s_haproxy' not in group_names"
        - "'ntp_server' not in group_names"
    - include_role:
        name: ntp/client/install
      when:
        - "enable_ntp_server"
        - "'cluster_boot_registry' not in group_names"
        - "'keepalived' not in group_names"
        - "'nameserver' not in group_names"
        - "'k8s_haproxy' not in group_names"
        - "'ntp_server' not in group_names"
    - include_role:
        name: nameserver/set-resolv-conf
      vars:
        enable_nameserver: false
      when:
        - "'cluster_boot_registry' not in group_names"
        - "'keepalived' not in group_names"
        - "'nameserver' not in group_names"
        - "'k8s_haproxy' not in group_names"
        - "'ntp_server' not in group_names"
    - include_role:
        name: certificate/uninstall-ca-cert
      when:
        - "'cluster_boot_registry' not in group_names"
        - "'keepalived' not in group_names"
        - "'nameserver' not in group_names"
        - "'k8s_haproxy' not in group_names"
        - "'ntp_server' not in group_names"

- hosts: k8s_haproxy
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - include_role:
        name: k8s-haproxy/uninstall
    - include_role:
        name: k8s-haproxy/install
      vars:
        backend_servers: "{{ groups['control_plane_k8s_node'] | difference(node) }}"
      when: enable_k8s_haproxy
