- hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - include_role:
        name: preflight/ensure-bin-directory-exist

- hosts: all:localhost
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - include_role:
        name: gather-facts

- hosts: tls_cert_issuer
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - include_role:
        name: certificate/set-ca-cert-variable

- hosts: k8s_haproxy
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - include_role:
        name: certificate/install-ca-cert
      vars:
        ca_cert: "{{ hostvars[groups['tls_cert_issuer'] | first]['ca_cert'] }}"
    - include_role:
        name: nameserver/set-resolv-conf
    - include_role:
        name: ntp-server/set-ntp-client-conf
    - name: Get docker service status
      ansible.builtin.systemd:
        name: "docker"
      register: service_status
    - include_role:
        name: docker/install
      when:
        - service_status.status.LoadState == "not-found"
    - include_role:
        name: k8s-haproxy/uninstall
    - include_role:
        name: k8s-haproxy/install
      when: enable_k8s_haproxy
