- hosts: localhost
  become: true
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - include_role:
        name: preflight/ensure-bin-directory-exist
    - name: Fail if node variable is invalid
      fail:
        msg: "node variable '{{ node | default('undefined') }}' is invalid host"
      when: node is undefined or
        node | length <= 0
    - name: Fail if node variable does not belong to k8s_node group
      fail:
        msg: "node variable '{{ node }}' does not belong to k8s_node group"
      when: node not in groups['k8s_node']

- hosts: all:localhost
  become: true
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - include_role:
        name: gather-facts

- hosts: tls_cert_issuer
  become: true
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - include_role:
        name: certificate/set-ca-cert-variable

- hosts: "{{ node }}"
  become: true
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - include_role:
        name: certificate/install-ca-cert
      vars:
        ca_cert: "{{ hostvars[groups['tls_cert_issuer'] | first]['ca_cert'] }}"
    - include_role:
        name: nameserver/set-resolv-conf
    - include_role:
        name: ntp/client/install
    - name: Get docker service status
      ansible.builtin.systemd:
        name: "docker"
      register: service_status
    - include_role:
        name: docker/install
      when:
        - service_status.status.LoadState == "not-found"
    - include_role:
        name: k8s/preflight
    - include_role:
        name: k8s/install-kubelet
    - include_role:
        name: k8s/attach-node

- hosts: k8s_haproxy
  become: true
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - include_role:
        name: k8s-haproxy/uninstall
    - include_role:
        name: k8s-haproxy/install
      when: enable_k8s_haproxy
