- hosts: localhost
  become: true
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - include_role:
        name: preflight/ensure-bin-directory-exist

- hosts: all:localhost
  become: true
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - include_role:
        name: gather-facts

- hosts: tls_cert_issuer
  become: true
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - include_role:
        name: certificate/set-ca-cert-variable

- hosts: keepalived
  become: true
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - include_role:
        name: certificate/install-ca-cert
      vars:
        ca_cert: "{{ hostvars[groups['tls_cert_issuer'] | first]['ca_cert'] }}"
    - include_role:
        name: nameserver/set-resolv-conf
    - block:
      - include_role:
          name: ntp/client/uninstall
      - include_role:
          name: ntp/client/install
      when: enable_ntp_server
    - name: Get docker service status
      ansible.builtin.systemd:
        name: "docker"
      register: service_status
    - include_role:
        name: docker/install
      when:
        - service_status.status.LoadState == "not-found"
    - include_role:
        name: keepalived/uninstall
    - include_role:
        name: keepalived/install
      when: enable_keepalived
