- hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - include_role:
        name: preflight/ensure-bin-directory-exist

- hosts: all:localhost
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - include_role:
        name: gather-facts

- hosts: docker_node
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - include_role:
        name: docker/test-linux-packages

- hosts: k8s_node
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - include_role:
        name: k8s/test-linux-packages
